// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

// Injectors from wire.go:

func InitializeAuthenticationService(phrase string) *AuthenticationServiceImpl {
	authenticationServiceImpl := AuthenticationServiceProvider(phrase)
	return authenticationServiceImpl
}

func InitializeEmailService(phrase string) *EmailServiceImpl {
	emailServiceImpl := EmailServiceProvider(phrase)
	return emailServiceImpl
}
