// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package authenticationService

import (
	"github.com/AFORANURAG/microServices/backend/apiGateway/pkg/clientProviders/authenticationServiceClient"
)

// Injectors from wire.go:

func InitializeAuthenticationService() *AuthenticationServiceImpl {
	authServiceAuthenticationServiceClient := authenticationServiceClient.AuthenticationServiceClientProvider()
	authenticationServiceImpl := AuthenticationServiceProvider(authServiceAuthenticationServiceClient)
	return authenticationServiceImpl
}
