// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package userService

// Injectors from wire.go:

func InitializeUserService(phrase string) *UserServiceImpl {
	userServiceImpl := UserServiceProvider()
	return userServiceImpl
}
