// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package userService

import (
	"github.com/AFORANURAG/microServices/authenticationService/services/dbService"
	"github.com/AFORANURAG/microServices/authenticationService/types/userServiceTypes"
	"github.com/AFORANURAG/microServices/authenticationService/userRepository"
)

// Injectors from wire.go:

func InitializeUserService(phrase userservicetypes.UserServicePhrase) UserService {
	mysqldbService := dbservice.NewDBServiceClientProvider(phrase)
	iUserRepository := userRepository.NewUserRepositoryProvider(mysqldbService)
	userService := NewUserServiceProvider(iUserRepository)
	return userService
}
