// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package userService

import (
	"github.com/AFORANURAG/microServices/userService/services/dbService"
	"github.com/AFORANURAG/microServices/userService/userRepository"
)

// Injectors from wire.go:

func InitializeUserService(phrase string) *UserServiceImpl {
	mysqldbService := dbservice.NewDBServiceClientProvider(phrase)
	userRepositoryUserRepository := userRepository.NewUserRepositoryProvider(mysqldbService)
	userServiceImpl := NewUserServiceProvider(userRepositoryUserRepository)
	return userServiceImpl
}
