// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package authService

import (
	"github.com/AFORANURAG/microServices/authenticationService/clientProviders/emailServiceClient"
	"github.com/AFORANURAG/microServices/authenticationService/services/queueService"
	"github.com/AFORANURAG/microServices/authenticationService/services/userService"
	"github.com/AFORANURAG/microServices/authenticationService/types/queueServiceTypes"
	"github.com/AFORANURAG/microServices/authenticationService/types/userServiceTypes"
)

// Injectors from wire.go:

func InitializeAuthenticationService(phrase1 userservicetypes.UserServicePhrase, phrase2 queueservicetypes.QueueServicePhrase) AuthenticationServiceServer {
	userServiceUserService := userService.InitializeUserService(phrase1)
	emailServiceClient := emailclient.NewEmailServiceServiceClientProvider()
	producer := queueservice.InitializeProducerService(phrase2)
	authenticationServiceServer := NewAuthenticationServiceProvider(userServiceUserService, emailServiceClient, producer)
	return authenticationServiceServer
}
