// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package authService

import (
	"github.com/AFORANURAG/microServices/authenticationService/clientProviders/emailServiceClient"
	"github.com/AFORANURAG/microServices/authenticationService/clientProviders/userServiceClient"
)

// Injectors from wire.go:

func InitializeAuthenticationService(phrase string) *AuthenticationServiceImpl {
	userServiceUserServiceClient := userServiceClient.NewUserServiceServiceClientProvider()
	emailServiceClient := emailclient.NewEmailServiceServiceClientProvider()
	authenticationServiceImpl := NewAuthenticationServiceProvider(userServiceUserServiceClient, emailServiceClient)
	return authenticationServiceImpl
}
