// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package authenticationService

// Injectors from wire.go:

func InitializeAuthenticationService() *AuthenticationServiceImpl {
	iUserService := UserServiceProvider()
	authenticationServiceImpl := AuthenticationServiceProvider(iUserService)
	return authenticationServiceImpl
}
